version: '3.8'

services:
  prueba-tecnica-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prueba-tecnica-api:latest
    container_name: prueba-tecnica-api-container
    ports:
      - "8080:8080"
    environment:
      # Configuración de la aplicación
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      
      # Configuración JWT
      - JWT_SECRET=myDockerSecretKey123456789012345678901234567890123456789012345678901234567890
      - JWT_EXPIRATION=86400000
      
      # Configuración de base de datos H2
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:notesdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      
      # Configuración de logging
      - LOGGING_LEVEL_COM_NOTES=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=WARN
    
    volumes:
      # Volumen para logs (opcional)
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    networks:
      - prueba-tecnica-network

networks:
  prueba-tecnica-network:
    driver: bridge

volumes:
  logs:
    driver: local
